apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
    giropops: strigus
spec:
  selector:
    app: giropops-senhas
    giropops: strigus
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  type: NodePort
