# templates/redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    giropops: strigus
spec:
  selector:
    app: redis
    giropops: strigus
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  type: ClusterIP
